language: java
dist: xenial
sudo: false

branches:
  except:
  - gh-pages

matrix:
  include:
  - name: "Java 8 Tests"
    jdk: openjdk8
    script: travis_retry mvn test
  - name: "Coverage"
    jdk: openjdk8
    env: TESTENV=cover FYI="this also builds documentation for tags"
    script: mvn clean cobertura:cobertura

after_success:
- '[[ "$TESTENV" == "cover" ]] && bash <(curl -s https://codecov.io/bash)'
