language: java
dist: bionic
sudo: false

branches:
  except:
  - gh-pages

env:
  global:
    - secure: zykjK55fskWbGJGQnG+T7ySSGShSGPnKMTk3hhdmLrV2Ou6oHk8eC1/puDfc97hHfuq1qtJV0cT5PcC8VdrJP+aaDKKuR6wnyroKPqToJbG2sanvSZ1fIICVLT6EB9cn6AFkHIwRMDDwgiDcm28IY8oRmxYt/EBSWRjT/z7pvRMRkf6YMRE/UfiVkop+SvTBAx+Xgr9Et+q5bj8okPHpaZ8aK4wazkxcABIqittQ73ydFwJxEt8KmsouK2yfYGgCpT/idGTn5RsmlVPP9b/Ls37KMWjbZSZgHUq11rrhgrZuVLtCgycu5utOFpuFKHg8vX9Ft804bbb0eW+eQkfBXqTrqasX5jIm5aevqM60x+U+Nc9iDzRS2HkMr1y5VDGdzCp0EVASaop4qy17ciE+lLr+aWnrqjnZy9Cxppnf/bg/BO3596MlSheQwMmlvocxXCcKvMZQa92f4yN4OV79jYAayXVFtVkhDuv/1eeJxzU8w93T+LOeOEc4DNLONOBNgFJ57mICMt2+fVx3Hnq4R8PsK5G39eHh8qUTN4Z8ZHnqE2CPBz3MWkPkv8OOTUFGlkYU6pp6gNQw0UqNzYJc8YMinxMT0APh2nR3aNpRvLzoq7B04IpNj4tUgnkA2gChssWH36ekK/qmhr9FRHpdgIek4tXlBD5lMLocY4WexnI=

addons:
  apt:
    update: true

matrix:
  include:
  - name: "Java 8 Tests"
    jdk: openjdk8
    script: travis_retry mvn test
  - name: "Coverage"
    jdk: openjdk8
    python:
      - "3.8"
    before_install:
      - sudo apt-get install python3-venv
    env: TESTENV=cover FYI="this also builds documentation for tags"
    script: mvn clean cobertura:cobertura

after_success:
  - '[[ "$TESTENV" == "cover" ]] && bash <(curl -s https://codecov.io/bash)'
  - '[[ "$TESTENV" == "cover" ]] && [[ -n "$TRAVIS_TAG" ]] && ./deploy-docs.sh'
